# imports
import streamlit as st
import pandas as pd
import plotly.express as px


# configuration
st.set_option('deprecation.showfileUploaderEncoding', False)
st.title("Student Feedback Visualisation App")

# add sidebar
st.sidebar.subheader("Visualisation settings")

# setup file upload
global df
uploaded_file = st.sidebar.file_uploader(label="Upload your CSV file", type = ['csv'])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    
    # show raw data
    if st.checkbox('Show raw data'):
        st.subheader('Raw data')
        st.write(df)
    
    # setup sidebar
    year_group = st.sidebar.selectbox('Year Group',['all year groups','Year 7','Year 8','Year 9','Year 10','Year 11','Year 12','Year 13'], key='1')
    teacher = st.sidebar.selectbox('Teacher',['all teachers','Mr Thomson','Ms Rivas','Ms Taylor','Mr Tang'],key='1') 

    
    # data filtering for Mr Thomson
    year_7_MrT = df[(df['Year Group']=='Year 7') & (df['Teacher']=='Mr Thomson')]
    year_7_MrT.head()
    year_8_MrT = df[(df['Year Group']=='Year 8') & (df['Teacher']=='Mr Thomson')]
    year_8_MrT.head()
    year_9_MrT = df[(df['Year Group']=='Year 9') & (df['Teacher']=='Mr Thomson')]
    year_9_MrT.head()
    year_10_MrT = df[(df['Year Group']=='Year 10') & (df['Teacher']=='Mr Thomson')]
    year_10_MrT.head()
    year_11_MrT = df[(df['Year Group']=='Year 11') & (df['Teacher']=='Mr Thomson')]
    year_11_MrT.head()
    year_12_MrT = df[(df['Year Group']=='Year 12') & (df['Teacher']=='Mr Thomson')]
    year_12_MrT.head()
    year_13_MrT = df[(df['Year Group']=='Year 13') & (df['Teacher']=='Mr Thomson')]
    year_13_MrT.head()
    all_years_MrT = df[(df['Teacher']=='Mr Thomson')]
    all_years_MrT.head()

    # data filtering for Ms Rivas
    year_7_MsR = df[(df['Year Group']=='Year 7') & (df['Teacher']=='Ms Rivas')]
    year_7_MsR.head()
    year_8_MsR = df[(df['Year Group']=='Year 8') & (df['Teacher']=='Ms Rivas')]
    year_8_MsR.head()
    year_9_MsR = df[(df['Year Group']=='Year 9') & (df['Teacher']=='Ms Rivas')]
    year_9_MsR.head()
    year_10_MsR = df[(df['Year Group']=='Year 10') & (df['Teacher']=='Ms Rivas')]
    year_10_MsR.head()
    year_11_MsR = df[(df['Year Group']=='Year 11') & (df['Teacher']=='Ms Rivas')]
    year_11_MsR.head()
    year_12_MsR = df[(df['Year Group']=='Year 12') & (df['Teacher']=='Ms Rivas')]
    year_12_MsR.head()
    year_13_MsR = df[(df['Year Group']=='Year 13') & (df['Teacher']=='Ms Rivas')]
    year_13_MsR.head()
    all_years_MsR = df[(df['Teacher']=='Ms Rivas')]
    all_years_MsR.head()

    # data filtering for Ms Taylor
    year_7_MsT = df[(df['Year Group']=='Year 7') & (df['Teacher']=='Ms Taylor')]
    year_7_MsT.head()
    year_8_MsT = df[(df['Year Group']=='Year 8') & (df['Teacher']=='Ms Taylor')]
    year_8_MsT.head()
    year_9_MsT = df[(df['Year Group']=='Year 9') & (df['Teacher']=='Ms Taylor')]
    year_9_MsT.head()
    year_10_MsT = df[(df['Year Group']=='Year 10') & (df['Teacher']=='Ms Taylor')]
    year_10_MsT.head()
    year_11_MsT = df[(df['Year Group']=='Year 11') & (df['Teacher']=='Ms Taylor')]
    year_11_MsT.head()
    year_12_MsT = df[(df['Year Group']=='Year 12') & (df['Teacher']=='Ms Taylor')]
    year_12_MsT.head()
    year_13_MsT = df[(df['Year Group']=='Year 13') & (df['Teacher']=='Ms Taylor')]
    year_13_MsT.head()
    all_years_MsT = df[(df['Teacher']=='Ms Taylor')]
    all_years_MsT.head()

    # data filtering for Mr Tang
    year_7_MrTang = df[(df['Year Group']=='Year 7') & (df['Teacher']=='Mr Tang')]
    year_7_MrTang.head()
    year_8_MrTang = df[(df['Year Group']=='Year 8') & (df['Teacher']=='Mr Tang')]
    year_8_MrTang.head()
    year_9_MrTang = df[(df['Year Group']=='Year 9') & (df['Teacher']=='Mr Tang')]
    year_9_MrTang.head()
    year_10_MrTang = df[(df['Year Group']=='Year 10') & (df['Teacher']=='Mr Tang')]
    year_10_MrTang.head()
    year_11_MrTang = df[(df['Year Group']=='Year 11') & (df['Teacher']=='Mr Tang')]
    year_11_MrTang.head()
    year_12_MrTang = df[(df['Year Group']=='Year 12') & (df['Teacher']=='Mr Tang')]
    year_12_MrTang.head()
    year_13_MrTang = df[(df['Year Group']=='Year 13') & (df['Teacher']=='Mr Tang')]
    year_13_MrTang.head()
    all_years_MrTang = df[(df['Teacher']=='Mr Tang')]
    all_years_MrTang.head()
    

    # overall display
    if year_group == 'all year groups' and teacher == 'all teachers':
        st.subheader("Overall lesson rating")
        fig_overall = px.pie(df, names='Q1')
        st.plotly_chart(fig_overall)

        
    # data display for Mr Thomson
    # Year 7
    if year_group == 'Year 7' and teacher == 'Mr Thomson':
        st.subheader("How would you rate your lesson overall?")
        fig1_7 = px.pie(year_7_MrT, names='Q1')
        st.plotly_chart(fig1_7)
        st.subheader("Was the lesson fun and interactive?")
        fig2_7 = px.pie(year_7_MrT, names='Q2')
        st.plotly_chart(fig2_7)
        st.subheader("Was the lesson content interesting and engaging?")
        fig3_7 = px.pie(year_7_MrT, names='Q3')
        st.plotly_chart(fig3_7)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig4_7 = px.pie(year_7_MrT, names='Q4')
        st.plotly_chart(fig4_7)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig5_7 = px.pie(year_7_MrT, names='Q5')
        st.plotly_chart(fig5_7)
        st.subheader("Pupil comments")
        comment_7 = (year_7_MrT['What do you think could have been better?'])
        st.write(comment_7) 
    # Year 8
    if year_group == 'Year 8' and teacher == 'Mr Thomson':
        st.subheader("How would you rate your lesson overall?")
        fig1_8 = px.pie(year_8_MrT, names='Q1')
        st.plotly_chart(fig1_8)
        st.subheader("Was the lesson fun and interactive?")
        fig2_8 = px.pie(year_8_MrT, names='Q2')
        st.plotly_chart(fig2_8)
        st.subheader("Was the lesson content interesting and engaging?")
        fig3_8 = px.pie(year_8_MrT, names='Q3')
        st.plotly_chart(fig3_8)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig4_8 = px.pie(year_8_MrT, names='Q4')
        st.plotly_chart(fig4_8)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig5_8 = px.pie(year_8_MrT, names='Q5')
        st.plotly_chart(fig5_8)
        st.subheader("Pupil comments")
        comment_8 = (year_8_MrT['What do you think could have been better?'])
        st.write(comment_8)
    # Year 9
    if year_group == 'Year 9' and teacher == 'Mr Thomson':
        st.subheader("How would you rate your lesson overall?")
        fig1_9 = px.pie(year_9_MrT, names='Q1')
        st.plotly_chart(fig1_9)
        st.subheader("Was the lesson fun and interactive?")
        fig2_9 = px.pie(year_9_MrT, names='Q2')
        st.plotly_chart(fig2_9)
        st.subheader("Was the lesson content interesting and engaging?")
        fig3_9 = px.pie(year_9_MrT, names='Q3')
        st.plotly_chart(fig3_9)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig4_9 = px.pie(year_9_MrT, names='Q4')
        st.plotly_chart(fig4_9)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig5_9 = px.pie(year_9_MrT, names='Q5')
        st.plotly_chart(fig5_9)
        st.subheader("Pupil comments")
        comment_9 = (year_9_MrT['What do you think could have been better?'])
        st.write(comment_9)
    # Year 10
    if year_group == 'Year 10' and teacher == 'Mr Thomson':
        st.subheader("How would you rate your lesson overall?")
        fig1_10 = px.pie(year_10_MrT, names='Q1')
        st.plotly_chart(fig1_10)
        st.subheader("Was the lesson fun and interactive?")
        fig2_10 = px.pie(year_10_MrT, names='Q2')
        st.plotly_chart(fig2_10)
        st.subheader("Was the lesson content interesting and engaging?")
        fig3_10 = px.pie(year_10_MrT, names='Q3')
        st.plotly_chart(fig3_10)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig4_10 = px.pie(year_10_MrT, names='Q4')
        st.plotly_chart(fig4_10)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig5_10 = px.pie(year_10_MrT, names='Q5')
        st.plotly_chart(fig5_10)
        st.subheader("Pupil comments")
        comment_10 = (year_10_MrT['What do you think could have been better?'])
        st.write(comment_10)
    # Year 11
    if year_group == 'Year 11' and teacher == 'Mr Thomson':
        st.subheader("How would you rate your lesson overall?")
        fig1_11 = px.pie(year_11_MrT, names='Q1')
        st.plotly_chart(fig1_11)
        st.subheader("Was the lesson fun and interactive?")
        fig2_11 = px.pie(year_11_MrT, names='Q2')
        st.plotly_chart(fig2_11)
        st.subheader("Was the lesson content interesting and engaging?")
        fig3_11 = px.pie(year_11_MrT, names='Q3')
        st.plotly_chart(fig3_11)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig4_11 = px.pie(year_11_MrT, names='Q4')
        st.plotly_chart(fig4_11)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig5_11 = px.pie(year_11_MrT, names='Q5')
        st.plotly_chart(fig5_11)
        st.subheader("Pupil comments")
        comment_11 = (year_11_MrT['What do you think could have been better?'])
        st.write(comment_11)
    # Year 12
    if year_group == 'Year 12' and teacher == 'Mr Thomson':
        st.subheader("How would you rate your lesson overall?")
        fig1_12 = px.pie(year_12_MrT, names='Q1')
        st.plotly_chart(fig1_12)
        st.subheader("Was the lesson fun and interactive?")
        fig2_12 = px.pie(year_12_MrT, names='Q2')
        st.plotly_chart(fig2_12)
        st.subheader("Was the lesson content interesting and engaging?")
        fig3_12 = px.pie(year_12_MrT, names='Q3')
        st.plotly_chart(fig3_12)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig4_12 = px.pie(year_12_MrT, names='Q4')
        st.plotly_chart(fig4_12)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig5_12 = px.pie(year_12_MrT, names='Q5')
        st.plotly_chart(fig5_12)
        st.subheader("Pupil comments")
        comment_12 = (year_12_MrT['What do you think could have been better?'])
        st.write(comment_12)
    # Year 13
    if year_group == 'Year 13' and teacher == 'Mr Thomson':
        st.subheader("How would you rate your lesson overall?")
        fig1_13 = px.pie(year_13_MrT, names='Q1')
        st.plotly_chart(fig1_13)
        st.subheader("Was the lesson fun and interactive?")
        fig2_13 = px.pie(year_13_MrT, names='Q2')
        st.plotly_chart(fig2_13)
        st.subheader("Was the lesson content interesting and engaging?")
        fig3_13 = px.pie(year_13_MrT, names='Q3')
        st.plotly_chart(fig3_13)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig4_13 = px.pie(year_13_MrT, names='Q4')
        st.plotly_chart(fig4_13)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig5_13 = px.pie(year_13_MrT, names='Q5')
        st.plotly_chart(fig5_13)
        st.subheader("Pupil comments")
        comment_13 = (year_13_MrT['What do you think could have been better?'])
        st.write(comment_13)
    # all year groups
    if year_group == 'all year groups' and teacher == 'Mr Thomson':
        st.subheader("Overall lesson rating")
        fig_all_MrT = px.pie(all_years_MrT, names='Q1')
        st.plotly_chart(fig_all_MrT)

    # data display for Ms Rivas
    # Year 7
    if year_group == 'Year 7' and teacher == 'Ms Rivas':
        st.subheader("How would you rate your lesson overall?")
        fig6_7 = px.pie(year_7_MsR, names='Q1')
        st.plotly_chart(fig6_7)
        st.subheader("Was the lesson fun and interactive?")
        fig7_7 = px.pie(year_7_MsR, names='Q2')
        st.plotly_chart(fig7_7)
        st.subheader("Was the lesson content interesting and engaging?")
        fig8_7 = px.pie(year_7_MsR, names='Q3')
        st.plotly_chart(fig8_7)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig9_7 = px.pie(year_7_MsR, names='Q4')
        st.plotly_chart(fig9_7)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig10_7 = px.pie(year_7_MsR, names='Q5')
        st.plotly_chart(fig10_7)
        st.subheader("Pupil comments")
        comment2_7 = (year_7_MsR['What do you think could have been better?'])
        st.write(comment2_7)       
    # Year 8
    if year_group == 'Year 8' and teacher == 'Ms Rivas':
        st.subheader("How would you rate your lesson overall?")
        fig6_8 = px.pie(year_8_MsR, names='Q1')
        st.plotly_chart(fig6_8)
        st.subheader("Was the lesson fun and interactive?")
        fig7_8 = px.pie(year_8_MsR, names='Q2')
        st.plotly_chart(fig7_8)
        st.subheader("Was the lesson content interesting and engaging?")
        fig8_8 = px.pie(year_8_MsR, names='Q3')
        st.plotly_chart(fig8_8)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig9_8 = px.pie(year_8_MsR, names='Q4')
        st.plotly_chart(fig9_8)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig10_8 = px.pie(year_8_MsR, names='Q5')
        st.plotly_chart(fig10_8)
        st.subheader("Pupil comments")
        comment2_8 = (year_8_MsR['What do you think could have been better?'])
        st.write(comment2_8) 
    # Year 9
    if year_group == 'Year 9' and teacher == 'Ms Rivas':
        st.subheader("How would you rate your lesson overall?")
        fig6_9 = px.pie(year_9_MsR, names='Q1')
        st.plotly_chart(fig6_9)
        st.subheader("Was the lesson fun and interactive?")
        fig7_9 = px.pie(year_9_MsR, names='Q2')
        st.plotly_chart(fig7_9)
        st.subheader("Was the lesson content interesting and engaging?")
        fig8_9 = px.pie(year_9_MsR, names='Q3')
        st.plotly_chart(fig8_9)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig9_9 = px.pie(year_9_MsR, names='Q4')
        st.plotly_chart(fig9_9)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig10_9 = px.pie(year_9_MsR, names='Q5')
        st.plotly_chart(fig10_9)
        st.subheader("Pupil comments")
        comment2_9 = (year_9_MsR['What do you think could have been better?'])
        st.write(comment2_9)
    # Year 10
    if year_group == 'Year 10' and teacher == 'Ms Rivas':
        st.subheader("How would you rate your lesson overall?")
        fig6_10 = px.pie(year_10_MsR, names='Q1')
        st.plotly_chart(fig6_10)
        st.subheader("Was the lesson fun and interactive?")
        fig7_10 = px.pie(year_10_MsR, names='Q2')
        st.plotly_chart(fig7_10)
        st.subheader("Was the lesson content interesting and engaging?")
        fig8_10 = px.pie(year_10_MsR, names='Q3')
        st.plotly_chart(fig8_10)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig9_10 = px.pie(year_10_MsR, names='Q4')
        st.plotly_chart(fig9_10)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig10_10 = px.pie(year_10_MsR, names='Q5')
        st.plotly_chart(fig10_10)
        st.subheader("Pupil comments")
        comment2_10 = (year_10_MsR['What do you think could have been better?'])
        st.write(comment2_10)
    # Year 11
    if year_group == 'Year 11' and teacher == 'Ms Rivas':
        st.subheader("How would you rate your lesson overall?")
        fig6_11 = px.pie(year_11_MsR, names='Q1')
        st.plotly_chart(fig6_11)
        st.subheader("Was the lesson fun and interactive?")
        fig7_11 = px.pie(year_11_MsR, names='Q2')
        st.plotly_chart(fig7_11)
        st.subheader("Was the lesson content interesting and engaging?")
        fig8_11 = px.pie(year_11_MsR, names='Q3')
        st.plotly_chart(fig8_11)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig9_11 = px.pie(year_11_MsR, names='Q4')
        st.plotly_chart(fig9_11)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig10_11 = px.pie(year_11_MsR, names='Q5')
        st.plotly_chart(fig10_11)
        st.subheader("Pupil comments")
        comment2_11 = (year_11_MsR['What do you think could have been better?'])
        st.write(comment2_11)
    # Year 12
    if year_group == 'Year 12' and teacher == 'Ms Rivas':
        st.subheader("How would you rate your lesson overall?")
        fig6_12 = px.pie(year_12_MsR, names='Q1')
        st.plotly_chart(fig6_12)
        st.subheader("Was the lesson fun and interactive?")
        fig7_12 = px.pie(year_12_MsR, names='Q2')
        st.plotly_chart(fig7_12)
        st.subheader("Was the lesson content interesting and engaging?")
        fig8_12 = px.pie(year_12_MsR, names='Q3')
        st.plotly_chart(fig8_12)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig9_12 = px.pie(year_12_MsR, names='Q4')
        st.plotly_chart(fig9_12)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig10_12 = px.pie(year_12_MsR, names='Q5')
        st.plotly_chart(fig10_12)
        st.subheader("Pupil comments")
        comment2_12 = (year_12_MsR['What do you think could have been better?'])
        st.write(comment2_12)
    # Year 13
    if year_group == 'Year 13' and teacher == 'Ms Rivas':
        st.subheader("How would you rate your lesson overall?")
        fig6_13 = px.pie(year_13_MsR, names='Q1')
        st.plotly_chart(fig6_13)
        st.subheader("Was the lesson fun and interactive?")
        fig7_13 = px.pie(year_13_MsR, names='Q2')
        st.plotly_chart(fig7_13)
        st.subheader("Was the lesson content interesting and engaging?")
        fig8_13 = px.pie(year_13_MsR, names='Q3')
        st.plotly_chart(fig8_13)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig9_13 = px.pie(year_13_MsR, names='Q4')
        st.plotly_chart(fig9_13)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig10_13 = px.pie(year_13_MsR, names='Q5')
        st.plotly_chart(fig10_13)
        st.subheader("Pupil comments")
        comment2_13 = (year_13_MsR['What do you think could have been better?'])
        st.write(comment2_13)
    # all year groups
    if year_group == 'all year groups' and teacher == 'Ms Rivas':
        st.subheader("Overall lesson rating")
        fig_all_MsR = px.pie(all_years_MsR, names='Q1')
        st.plotly_chart(fig_all_MsR)

    # data display for Ms Taylor
    # Year 7
    if year_group == 'Year 7' and teacher == 'Ms Taylor':
        st.subheader("How would you rate your lesson overall?")
        fig11_7 = px.pie(year_7_MsT, names='Q1')
        st.plotly_chart(fig11_7)
        st.subheader("Was the lesson fun and interactive?")
        fig12_7 = px.pie(year_7_MsT, names='Q2')
        st.plotly_chart(fig12_7)
        st.subheader("Was the lesson content interesting and engaging?")
        fig13_7 = px.pie(year_7_MsT, names='Q3')
        st.plotly_chart(fig13_7)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig14_7 = px.pie(year_7_MsT, names='Q4')
        st.plotly_chart(fig14_7)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig15_7 = px.pie(year_7_MsT, names='Q5')
        st.plotly_chart(fig15_7)
        st.subheader("Pupil comments")
        comment3_7 = (year_7_MsT['What do you think could have been better?'])
        st.write(comment3_7)
    # Year 8
    if year_group == 'Year 8' and teacher == 'Ms Taylor':
        st.subheader("How would you rate your lesson overall?")
        fig11_8 = px.pie(year_8_MsT, names='Q1')
        st.plotly_chart(fig11_8)
        st.subheader("Was the lesson fun and interactive?")
        fig12_8 = px.pie(year_8_MsT, names='Q2')
        st.plotly_chart(fig12_8)
        st.subheader("Was the lesson content interesting and engaging?")
        fig13_8 = px.pie(year_8_MsT, names='Q3')
        st.plotly_chart(fig13_8)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig14_8 = px.pie(year_8_MsT, names='Q4')
        st.plotly_chart(fig14_8)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig15_8 = px.pie(year_8_MsT, names='Q5')
        st.plotly_chart(fig15_8)
        st.subheader("Pupil comments")
        comment3_8 = (year_8_MsT['What do you think could have been better?'])
        st.write(comment3_8)
    # Year 9
    if year_group == 'Year 9' and teacher == 'Ms Taylor':
        st.subheader("How would you rate your lesson overall?")
        fig11_9 = px.pie(year_9_MsT, names='Q1')
        st.plotly_chart(fig11_9)
        st.subheader("Was the lesson fun and interactive?")
        fig12_9 = px.pie(year_9_MsT, names='Q2')
        st.plotly_chart(fig12_9)
        st.subheader("Was the lesson content interesting and engaging?")
        fig13_9 = px.pie(year_9_MsT, names='Q3')
        st.plotly_chart(fig13_9)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig14_9 = px.pie(year_9_MsT, names='Q4')
        st.plotly_chart(fig14_9)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig15_9 = px.pie(year_9_MsT, names='Q5')
        st.plotly_chart(fig15_9)
        st.subheader("Pupil comments")
        comment3_9 = (year_9_MsT['What do you think could have been better?'])
        st.write(comment3_9)
    # Year 10
    if year_group == 'Year 10' and teacher == 'Ms Taylor':
        st.subheader("How would you rate your lesson overall?")
        fig11_10 = px.pie(year_10_MsT, names='Q1')
        st.plotly_chart(fig11_10)
        st.subheader("Was the lesson fun and interactive?")
        fig12_10 = px.pie(year_10_MsT, names='Q2')
        st.plotly_chart(fig12_10)
        st.subheader("Was the lesson content interesting and engaging?")
        fig13_10 = px.pie(year_10_MsT, names='Q3')
        st.plotly_chart(fig13_10)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig14_10 = px.pie(year_10_MsT, names='Q4')
        st.plotly_chart(fig14_10)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig15_10 = px.pie(year_10_MsT, names='Q5')
        st.plotly_chart(fig15_10)
        st.subheader("Pupil comments")
        comment3_10 = (year_10_MsT['What do you think could have been better?'])
        st.write(comment3_10)
    # Year 11
    if year_group == 'Year 11' and teacher == 'Ms Taylor':
        st.subheader("How would you rate your lesson overall?")
        fig11_11 = px.pie(year_11_MsT, names='Q1')
        st.plotly_chart(fig11_11)
        st.subheader("Was the lesson fun and interactive?")
        fig12_11 = px.pie(year_11_MsT, names='Q2')
        st.plotly_chart(fig12_11)
        st.subheader("Was the lesson content interesting and engaging?")
        fig13_11 = px.pie(year_11_MsT, names='Q3')
        st.plotly_chart(fig13_11)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig14_11 = px.pie(year_11_MsT, names='Q4')
        st.plotly_chart(fig14_11)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig15_11 = px.pie(year_11_MsT, names='Q5')
        st.plotly_chart(fig15_11)
        st.subheader("Pupil comments")
        comment3_11 = (year_11_MsT['What do you think could have been better?'])
        st.write(comment3_11)
    # Year 12
    if year_group == 'Year 12' and teacher == 'Ms Taylor':
        st.subheader("How would you rate your lesson overall?")
        fig11_12 = px.pie(year_12_MsT, names='Q1')
        st.plotly_chart(fig11_12)
        st.subheader("Was the lesson fun and interactive?")
        fig12_12 = px.pie(year_12_MsT, names='Q2')
        st.plotly_chart(fig12_12)
        st.subheader("Was the lesson content interesting and engaging?")
        fig13_12 = px.pie(year_12_MsT, names='Q3')
        st.plotly_chart(fig13_12)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig14_12 = px.pie(year_12_MsT, names='Q4')
        st.plotly_chart(fig14_12)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig15_12 = px.pie(year_12_MsT, names='Q5')
        st.plotly_chart(fig15_12)
        st.subheader("Pupil comments")
        comment3_12 = (year_12_MsT['What do you think could have been better?'])
        st.write(comment3_12)
    # Year 13
    if year_group == 'Year 13' and teacher == 'Ms Taylor':
        st.subheader("How would you rate your lesson overall?")
        fig11_13 = px.pie(year_13_MsT, names='Q1')
        st.plotly_chart(fig11_13)
        st.subheader("Was the lesson fun and interactive?")
        fig12_13 = px.pie(year_13_MsT, names='Q2')
        st.plotly_chart(fig12_13)
        st.subheader("Was the lesson content interesting and engaging?")
        fig13_13 = px.pie(year_13_MsT, names='Q3')
        st.plotly_chart(fig13_13)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig14_13 = px.pie(year_13_MsT, names='Q4')
        st.plotly_chart(fig14_13)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig15_13 = px.pie(year_13_MsT, names='Q5')
        st.plotly_chart(fig15_13)
        st.subheader("Pupil comments")
        comment3_13 = (year_13_MsT['What do you think could have been better?'])
        st.write(comment3_13)
    # all year groups
    if year_group == 'all year groups' and teacher == 'Ms Taylor':
        st.subheader("Overall lesson rating")
        fig_all_MsT = px.pie(all_years_MsT, names='Q1')
        st.plotly_chart(fig_all_MsT)
    
    # data display for Mr Tang
    # Year 7
    if year_group == 'Year 7' and teacher == 'Mr Tang':
        st.subheader("How would you rate your lesson overall?")
        fig16_7 = px.pie(year_7_MrTang, names='Q1')
        st.plotly_chart(fig16_7)
        st.subheader("Was the lesson fun and interactive?")
        fig17_7 = px.pie(year_7_MrTang, names='Q2')
        st.plotly_chart(fig17_7)
        st.subheader("Was the lesson content interesting and engaging?")
        fig18_7 = px.pie(year_7_MrTang, names='Q3')
        st.plotly_chart(fig18_7)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig19_7 = px.pie(year_7_MrTang, names='Q4')
        st.plotly_chart(fig19_7)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig20_7 = px.pie(year_7_MrTang, names='Q5')
        st.plotly_chart(fig20_7)
        st.subheader("Pupil comments")
        comment4_7 = (year_7_MrTang['What do you think could have been better?'])
        st.write(comment4_7) 
    # Year 8
    if year_group == 'Year 8' and teacher == 'Mr Tang':
        st.subheader("How would you rate your lesson overall?")
        fig16_8 = px.pie(year_8_MrTang, names='Q1')
        st.plotly_chart(fig16_8)
        st.subheader("Was the lesson fun and interactive?")
        fig17_8 = px.pie(year_8_MrTang, names='Q2')
        st.plotly_chart(fig17_8)
        st.subheader("Was the lesson content interesting and engaging?")
        fig18_8 = px.pie(year_8_MrTang, names='Q3')
        st.plotly_chart(fig18_8)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig19_8 = px.pie(year_8_MrTang, names='Q4')
        st.plotly_chart(fig19_8)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig20_8 = px.pie(year_8_MrTang, names='Q5')
        st.plotly_chart(fig20_8)
        st.subheader("Pupil comments")
        comment4_8 = (year_8_MrTang['What do you think could have been better?'])
        st.write(comment4_8)
    # Year 9
    if year_group == 'Year 9' and teacher == 'Mr Tang':
        st.subheader("How would you rate your lesson overall?")
        fig16_9 = px.pie(year_9_MrTang, names='Q1')
        st.plotly_chart(fig16_9)
        st.subheader("Was the lesson fun and interactive?")
        fig17_9 = px.pie(year_9_MrTang, names='Q2')
        st.plotly_chart(fig17_9)
        st.subheader("Was the lesson content interesting and engaging?")
        fig18_9 = px.pie(year_9_MrTang, names='Q3')
        st.plotly_chart(fig18_9)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig19_9 = px.pie(year_9_MrTang, names='Q4')
        st.plotly_chart(fig19_9)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig20_9 = px.pie(year_9_MrTang, names='Q5')
        st.plotly_chart(fig20_9)
        st.subheader("Pupil comments")
        comment4_9 = (year_9_MrTang['What do you think could have been better?'])
        st.write(comment4_9)
    # Year 10
    if year_group == 'Year 10' and teacher == 'Mr Tang':
        st.subheader("How would you rate your lesson overall?")
        fig16_10 = px.pie(year_10_MrTang, names='Q1')
        st.plotly_chart(fig16_10)
        st.subheader("Was the lesson fun and interactive?")
        fig17_10 = px.pie(year_10_MrTang, names='Q2')
        st.plotly_chart(fig17_10)
        st.subheader("Was the lesson content interesting and engaging?")
        fig18_10 = px.pie(year_10_MrTang, names='Q3')
        st.plotly_chart(fig18_10)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig19_10 = px.pie(year_10_MrTang, names='Q4')
        st.plotly_chart(fig19_10)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig20_10 = px.pie(year_10_MrTang, names='Q5')
        st.plotly_chart(fig20_10)
        st.subheader("Pupil comments")
        comment4_10 = (year_10_MrTang['What do you think could have been better?'])
        st.write(comment4_10)
    # Year 11
    if year_group == 'Year 11' and teacher == 'Mr Tang':
        st.subheader("How would you rate your lesson overall?")
        fig16_11 = px.pie(year_11_MrTang, names='Q1')
        st.plotly_chart(fig16_11)
        st.subheader("Was the lesson fun and interactive?")
        fig17_11 = px.pie(year_11_MrTang, names='Q2')
        st.plotly_chart(fig17_11)
        st.subheader("Was the lesson content interesting and engaging?")
        fig18_11 = px.pie(year_11_MrTang, names='Q3')
        st.plotly_chart(fig18_11)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig19_11 = px.pie(year_11_MrTang, names='Q4')
        st.plotly_chart(fig19_11)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig20_11 = px.pie(year_11_MrTang, names='Q5')
        st.plotly_chart(fig20_11)
        st.subheader("Pupil comments")
        comment4_11 = (year_11_MrTang['What do you think could have been better?'])
        st.write(comment4_11)
    # Year 12
    if year_group == 'Year 12' and teacher == 'Mr Tang':
        st.subheader("How would you rate your lesson overall?")
        fig16_12 = px.pie(year_12_MrTang, names='Q1')
        st.plotly_chart(fig16_12)
        st.subheader("Was the lesson fun and interactive?")
        fig17_12 = px.pie(year_12_MrTang, names='Q2')
        st.plotly_chart(fig17_12)
        st.subheader("Was the lesson content interesting and engaging?")
        fig18_12 = px.pie(year_12_MrTang, names='Q3')
        st.plotly_chart(fig18_12)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig19_12 = px.pie(year_12_MrTang, names='Q4')
        st.plotly_chart(fig19_12)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig20_12 = px.pie(year_12_MrTang, names='Q5')
        st.plotly_chart(fig20_12)
        st.subheader("Pupil comments")
        comment4_12 = (year_12_MrTang['What do you think could have been better?'])
        st.write(comment4_12)
    # Year 13
    if year_group == 'Year 13' and teacher == 'Mr Tang':
        st.subheader("How would you rate your lesson overall?")
        fig16_13 = px.pie(year_13_MrTang, names='Q1')
        st.plotly_chart(fig16_13)
        st.subheader("Was the lesson fun and interactive?")
        fig17_13 = px.pie(year_13_MrTang, names='Q2')
        st.plotly_chart(fig17_13)
        st.subheader("Was the lesson content interesting and engaging?")
        fig18_13 = px.pie(year_13_MrTang, names='Q3')
        st.plotly_chart(fig18_13)
        st.subheader("Were you comfortable with the pace of the lesson?")
        fig19_13 = px.pie(year_13_MrTang, names='Q4')
        st.plotly_chart(fig19_13)
        st.subheader("Did your teacher explore the real-world applications of what you learnt?")
        fig20_13 = px.pie(year_13_MrTang, names='Q5')
        st.plotly_chart(fig20_13)
        st.subheader("Pupil comments")
        comment4_13 = (year_13_MrTang['What do you think could have been better?'])
        st.write(comment4_13)
    # all year groups
    if year_group == 'all year groups' and teacher == 'Mr Tang':
        st.subheader("Overall lesson rating")
        fig_all_MrTang = px.pie(all_years_MrTang, names='Q1')
        st.plotly_chart(fig_all_MrTang)
